server:
  port: 8080

spring:
  application:
    name: news
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/news
    username: news
    password: NEWS_password
    hikari:
      schema: news_schema
      connection-ini-sql: CREATE SCHEMA IF NOT EXISTS news_schema;
      connection-timeout: 10000

logging:
  level:
    org:
      example:
        news: DEBUG

